# Generated by Django 4.2.5 on 2024-11-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bidang",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama_bidang", models.CharField(max_length=255)),
            ],
        ),
    ]
