# Generated by Django 4.2.5 on 2024-11-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bidang",
            options={"ordering": ["nama_bidang"], "verbose_name_plural": "Bidang"},
        ),
    ]
