# Generated by Django 4.2.5 on 2024-11-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0002_alter_bidang_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bidang",
            options={"ordering": ["id"], "verbose_name_plural": "Bidang"},
        ),
        migrations.RenameField(
            model_name="bidang",
            old_name="nama_bidang",
            new_name="nama",
        ),
    ]
