# Generated by Django 4.2.5 on 2024-11-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0004_bidang_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidang",
            name="user",
        ),
    ]
