# Generated by Django 4.2.5 on 2024-11-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0007_alter_pegawai_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kriteria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=100)),
                ("bobot", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Kriteria",
                "ordering": ["nama"],
            },
        ),
    ]
