# Generated by Django 4.2.5 on 2024-11-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0010_kriteria_tipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penilaian",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nilai", models.TextField(blank=True, null=True)),
                (
                    "bidang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testing.bidang"
                    ),
                ),
                (
                    "nama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testing.pegawai",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Penilaian",
                "ordering": ["id"],
            },
        ),
    ]
