# Generated by Django 4.2.5 on 2024-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0011_penilaian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penilaian",
            name="nilai",
            field=models.CharField(default="[]", max_length=255),
        ),
    ]
