# Generated by Django 4.2.5 on 2024-11-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0013_alter_penilaian_nilai"),
    ]

    operations = [
        migrations.CreateModel(
            name="PegawaiTerbaik",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=100)),
                ("bidang", models.CharField(max_length=100)),
                ("normalisasi_nilai", models.FloatField()),
                ("nilai_preferensi", models.FloatField()),
                ("tahun_penilaian", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Pegawai Terbaik",
                "ordering": ["-tahun_penilaian", "-nilai_preferensi"],
            },
        ),
    ]
