# Generated by Django 4.2.5 on 2024-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0014_pegawaiterbaik"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pegawaiterbaik",
            name="normalisasi_nilai",
            field=models.TextField(),
        ),
    ]
