# Generated by Django 4.2.5 on 2024-12-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0015_alter_pegawaiterbaik_normalisasi_nilai"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiwayatPegawaiTerbaik",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=100)),
                ("bidang", models.CharField(max_length=100)),
                ("normalisasi_nilai", models.TextField()),
                ("nilai_preferensi", models.FloatField()),
                ("tahun_penilaian", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Riwayat Pegawai Terbaik",
                "ordering": ["-tahun_penilaian", "-nilai_preferensi"],
            },
        ),
        migrations.CreateModel(
            name="RiwayatPenilaian",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nilai", models.TextField()),
                ("tahun_penilaian", models.IntegerField()),
                (
                    "bidang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testing.bidang"
                    ),
                ),
                (
                    "nama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testing.pegawai",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Riwayat Penilaian",
                "ordering": ["id"],
            },
        ),
    ]
