# Generated by Django 4.2.5 on 2024-12-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0016_riwayatpegawaiterbaik_riwayatpenilaian"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RiwayatPegawaiTerbaik",
        ),
    ]
